### ISSUE TITLE
season() and trend() functions do not exist 

### ISSUE THREAD

**Issue by dwhdai** [robjhyndman/fpp3-package#2]
The `season()` and `trend()` functions referenced throughout the book do not seem to be in any of the fpp3 referenced packages. Are they in another package?

**Comment by mitchelloharawild** [comment]
These are functions specific to each model, which are listed in the 'Specials' section of each model's help file. In particular, these specials relate to `xreg` which describes support for common regressors documented here: http://fable.tidyverts.org/reference/common_xregs.html
