### ISSUE TITLE
code for multivariate time series with mixture of continues and categorical data

### ISSUE THREAD

**Issue by Sandy4321** [robjhyndman/fpp3-package#3]
great book
but do you have code for multivariate time series with mixture of continues and categorical data pls?

**Comment by robjhyndman** [comment]
The multivariate section is available here: https://otexts.com/fpp3/VAR.html

**Comment by Sandy4321** [comment]
great 
thanks for answer
but  question was: 
will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

			color        weight     gender  height  age      target 
time 1|    black       56             m   160    34         yes
time 2|    white       77             f   170    54         no
time 3|   yellow      87             m   167    43          yes
time 4|    white       55             m   198    72         no
time 5|   white       88              f   176    32         yes

etc

Thank you very much in advance for detailed answer ....

**Comment by robjhyndman** [comment]
I don't know of any models that are truly multivariate and handle mixed type variables. Perhaps you want to model one of the numerical variables and use the others as covariates. In that case, look at dynamic regression models https://otexts.com/fpp3/dynamic.html

**Comment by Sandy4321** [comment]
it is very strange no body works on this kind of problems

please keep me updated if you find some kind of solution in future
