### ISSUE TITLE
Error in library

### ISSUE THREAD

**Issue by VictoriaVGTU** [robjhyndman/fpp3-package#6]
When I try to load fpp3 package it is written "Error in library(fpp3) : there is no package called ‘fpp3’". Could you help me with this issue?

**Comment by mitchelloharawild** [comment]
Seems like fpp3 isn't installed. Can you try `install.packages("fpp3")` and share the result?

**Comment by VictoriaVGTU** [comment]
I've tried it several times, however, the same error appears "Error in library(fpp3) : there is no package called ‘fpp3’"

**Comment by mitchelloharawild** [comment]
Can you share what messages you get when you run `install.packages("fpp3")`? (not `library(fpp3)`, but `install.packages("fpp3")`)

**Comment by VictoriaVGTU** [comment]
The message is as follows:

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Dell/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependencies ‘BH’, ‘generics’, ‘tidyselect’, ‘distributional’, ‘progressr’, ‘slider’, ‘cpp11’, ‘anytime’, ‘dplyr’, ‘fable’, ‘fabletools’, ‘feasts’, ‘lubridate’, ‘purrr’, ‘tidyr’, ‘tsibble’, ‘tsibbledata’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/BH_1.72.0-3.zip'
Content type 'application/zip' length 18270723 bytes (17.4 MB)
downloaded 17.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/generics_0.1.0.zip'
Content type 'application/zip' length 71381 bytes (69 KB)
downloaded 69 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tidyselect_1.1.0.zip'
Content type 'application/zip' length 202882 bytes (198 KB)
downloaded 198 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/distributional_0.2.1.zip'
Content type 'application/zip' length 478313 bytes (467 KB)
downloaded 467 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/progressr_0.6.0.zip'
Content type 'application/zip' length 199084 bytes (194 KB)
downloaded 194 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/slider_0.1.5.zip'
Content type 'application/zip' length 271069 bytes (264 KB)
downloaded 264 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/cpp11_0.2.4.zip'
Content type 'application/zip' length 179177 bytes (174 KB)
downloaded 174 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/anytime_0.3.9.zip'
Content type 'application/zip' length 1194899 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/dplyr_1.0.2.zip'
Content type 'application/zip' length 1306496 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/fable_0.2.1.zip'
Content type 'application/zip' length 1442565 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/fabletools_0.2.1.zip'
Content type 'application/zip' length 592576 bytes (578 KB)
downloaded 578 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/feasts_0.1.5.zip'
Content type 'application/zip' length 1158522 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/lubridate_1.7.9.2.zip'
Content type 'application/zip' length 1751377 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/purrr_0.3.4.zip'
Content type 'application/zip' length 428682 bytes (418 KB)
downloaded 418 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tidyr_1.1.2.zip'
Content type 'application/zip' length 1051447 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tsibble_0.9.3.zip'
Content type 'application/zip' length 1110566 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tsibbledata_0.2.0.zip'
Content type 'application/zip' length 2158732 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/fpp3_0.3.zip'
Content type 'application/zip' length 290257 bytes (283 KB)
downloaded 283 KB

**Comment by mitchelloharawild** [comment]
That's not the complete log, but it gives a suggestion for something you might need:

> WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
> 
> https://cran.rstudio.com/bin/windows/Rtools/

If you're installing from sources, you may need to compile some code in the package, which requires Rtools. If you install from CRAN, there should be some pre-compiled binaries for the packages which doesn't require Rtools.

Try installing Rtools and then install again.

**Comment by VictoriaVGTU** [comment]
I've installed RTools, but still cannot install fpp3. There were no such problems with installing fpp2.

Installing package into ‘C:/Users/Dell/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependencies ‘BH’, ‘generics’, ‘tidyselect’, ‘distributional’, ‘progressr’, ‘slider’, ‘cpp11’, ‘anytime’, ‘dplyr’, ‘fable’, ‘fabletools’, ‘feasts’, ‘lubridate’, ‘purrr’, ‘tidyr’, ‘tsibble’, ‘tsibbledata’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/BH_1.72.0-3.zip'
Content type 'application/zip' length 18270723 bytes (17.4 MB)
downloaded 17.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/generics_0.1.0.zip'
Content type 'application/zip' length 71381 bytes (69 KB)
downloaded 69 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tidyselect_1.1.0.zip'
Content type 'application/zip' length 202882 bytes (198 KB)
downloaded 198 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/distributional_0.2.1.zip'
Content type 'application/zip' length 478313 bytes (467 KB)
downloaded 467 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/progressr_0.6.0.zip'
Content type 'application/zip' length 199084 bytes (194 KB)
downloaded 194 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/slider_0.1.5.zip'
Content type 'application/zip' length 271069 bytes (264 KB)
downloaded 264 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/cpp11_0.2.4.zip'
Content type 'application/zip' length 179177 bytes (174 KB)
downloaded 174 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/anytime_0.3.9.zip'
Content type 'application/zip' length 1194899 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/dplyr_1.0.2.zip'
Content type 'application/zip' length 1306496 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/fable_0.2.1.zip'
Content type 'application/zip' length 1442565 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/fabletools_0.2.1.zip'
Content type 'application/zip' length 592576 bytes (578 KB)
downloaded 578 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/feasts_0.1.5.zip'
Content type 'application/zip' length 1158522 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/lubridate_1.7.9.2.zip'
Content type 'application/zip' length 1751377 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/purrr_0.3.4.zip'
Content type 'application/zip' length 428682 bytes (418 KB)
downloaded 418 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tidyr_1.1.2.zip'
Content type 'application/zip' length 1051447 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tsibble_0.9.3.zip'
Content type 'application/zip' length 1110566 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tsibbledata_0.2.0.zip'
Content type 'application/zip' length 2158732 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/fpp3_0.3.zip'
Content type 'application/zip' length 290257 bytes (283 KB)
downloaded 283 KB

**Comment by mitchelloharawild** [comment]
Now that you have Rtools installed, what happens when you install from sources?

`remotes::install_github("robjhyndman/fpp3-package")`

**Comment by VictoriaVGTU** [comment]
The same error... I even deleted and reinstalled R but still, fpp3 doesn't work.

**Comment by VictoriaVGTU** [comment]
I've even tried installing fpp3 on several computers, but the same error appears.
